import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, Bell, CheckCircle2, ClipboardCheck, ClipboardList, Database, Package, ShieldAlert, Wrench } from "lucide-react";
import { useApp } from "../store/store";
import { getDashboardSummary, listNotifications, listPlatformTenants } from "../lib/dashboard";
import { listRequests } from "../lib/requests";
import { listWorkOrders } from "../lib/workorders";
import { Card, Pill, Reveal, StatCard, statusTone } from "../components/kit";

const pretty = (v) => String(v || "-").split("_").map((x) => x[0] + x.slice(1).toLowerCase()).join(" ");
const date = (v) => v ? new Intl.DateTimeFormat("id-ID", { day: "numeric", month: "short", year: "numeric" }).format(new Date(v)) : "No due date";
const COLORS = ["#2563eb", "#8b5cf6", "#f59e0b", "#ef4444", "#10b981", "#94a3b8"];

function LoadingDashboard() { return <div className="space-y-4 animate-pulse"><div className="h-10 rounded-xl bg-muted" /><div className="grid grid-cols-4 gap-4">{[1, 2, 3, 4].map((x) => <div key={x} className="h-28 rounded-xl bg-muted" />)}</div><div className="h-72 rounded-xl bg-muted" /></div>; }
function ErrorState({ error, retry }) { return <Card className="border-destructive/30"><div className="flex gap-3"><ShieldAlert className="h-5 w-5 text-destructive" /><div><b>Dashboard could not be loaded</b><p className="mt-1 text-sm text-muted-foreground">{error}</p><button className="mt-3 text-sm font-semibold text-primary" onClick={retry}>Try again</button></div></div></Card>; }
function MiniTitle({ children, link, to }) { return <div className="mb-3 flex items-center justify-between"><h2 className="font-display text-sm font-bold">{children}</h2>{link && <Link to={to || "#"} className="text-[11px] font-semibold text-primary">{link}</Link>}</div>; }

function TenantDashboard() {
  const [summary, setSummary] = useState(null), [notifications, setNotifications] = useState([]), [requests, setRequests] = useState([]), [orders, setOrders] = useState([]), [error, setError] = useState("");
  const load = async () => { setError(""); setSummary(null); try { const [dash, notifs, requestRes, orderRes] = await Promise.all([getDashboardSummary(), listNotifications(), listRequests(), listWorkOrders()]); setSummary(dash.data); setNotifications(notifs.data || []); setRequests(requestRes.data || []); setOrders(orderRes.data || []); } catch (e) { setError(e.message || "An unexpected error occurred."); } };
  useEffect(() => { load(); }, []); if (!summary && !error) return <LoadingDashboard />; if (error) return <ErrorState error={error} retry={load} />;
  const assets = summary.assets || { total: 0, by_status: {} }, work = summary.work_orders || {}, latest = orders.length ? orders.slice(0, 5) : (work.latest || []);
  const orderStatus = orders.reduce((all, order) => ({ ...all, [order.status || "OPEN"]: (all[order.status || "OPEN"] || 0) + 1 }), {});
  const statusData = Object.entries(Object.keys(orderStatus).length ? orderStatus : (work.by_status || {})).map(([name, value]) => ({ name: pretty(name), value })).filter((v) => v.value > 0);
  const requestStatus = requests.reduce((all, request) => ({ ...all, [request.status || "SUBMITTED"]: (all[request.status || "SUBMITTED"] || 0) + 1 }), {});
  const monthKeys = Array.from({ length: 6 }, (_, i) => { const d = new Date(); d.setMonth(d.getMonth() - 5 + i); return d; });
  const chartData = monthKeys.map((d) => { const sameMonth = (value) => { const item = value && new Date(value); return item && item.getMonth() === d.getMonth() && item.getFullYear() === d.getFullYear(); }; return { name: d.toLocaleString("en", { month: "short" }), created: orders.filter((o) => sameMonth(o.created_at)).length, completed: orders.filter((o) => ["COMPLETED", "CLOSED", "VERIFIED"].includes(o.status) && sameMonth(o.completed_at || o.updated_at)).length }; });
  return <div className="mx-auto max-w-[1200px] space-y-4">
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatCard icon={Wrench} label="OPEN WORK ORDERS" value={work.active || 0} hint="Across all sites" /><StatCard icon={ClipboardCheck} label="PENDING APPROVAL" value={(summary.pending_request_approvals || 0) + (summary.pending_work_order_approvals || 0)} tone="warning" hint="Awaiting action" /><StatCard icon={Package} label="ASSETS UNDER MAINTENANCE" value={assets.by_status?.UNDER_MAINTENANCE || 0} tone="accent" hint="Requiring attention" /><StatCard icon={CheckCircle2} label="PM COMPLIANCE" value="87%" tone="success" delta="↗ 5% improvement" hint="Last 30 days" /></div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><MiniTitle>Work orders — last 6 months</MiniTitle><p className="-mt-2 mb-3 text-[11px] text-muted-foreground">Created vs completed</p><ResponsiveContainer width="100%" height={180}><BarChart data={chartData} barGap={4}><XAxis dataKey="name" tickLine={false} axisLine={false} fontSize={10} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} fontSize={10} /><Tooltip /><Bar dataKey="created" fill="#bfdbfe" radius={[3, 3, 0, 0]} /><Bar dataKey="completed" fill="#2563eb" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer><div className="flex justify-center gap-4 text-[10px] text-muted-foreground"><span>■ Created</span><span className="text-primary">■ Completed</span></div></Card><Card><MiniTitle>Work order status</MiniTitle>{statusData.length ? <><ResponsiveContainer width="100%" height={120}><PieChart><Pie data={statusData} dataKey="value" nameKey="name" innerRadius={37} outerRadius={57} paddingAngle={2}>{statusData.map((e, i) => <Cell key={e.name} fill={COLORS[i % COLORS.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="grid grid-cols-2 gap-y-1 text-[10px]">{statusData.map((s, i) => <span key={s.name} className="flex items-center justify-between text-muted-foreground"><i className="mr-1 h-1.5 w-1.5 rounded-full" style={{ backgroundColor: COLORS[i % COLORS.length] }} />{s.name}<b>{s.value}</b></span>)}</div></> : <p className="py-14 text-center text-xs text-muted-foreground">No work orders yet.</p>}</Card></div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-5"><Card className="lg:col-span-2"><MiniTitle>Request status</MiniTitle>{Object.keys(requestStatus).length ? <><ResponsiveContainer width="100%" height={130}><PieChart><Pie data={Object.entries(requestStatus).map(([name, value]) => ({ name: pretty(name), value }))} dataKey="value" nameKey="name" outerRadius={54}>{Object.keys(requestStatus).map((key, i) => <Cell key={key} fill={COLORS[i % COLORS.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="grid grid-cols-2 gap-y-1 text-[10px]">{Object.entries(requestStatus).map(([name, value], i) => <span key={name} className="flex items-center text-muted-foreground"><i className="mr-1 h-1.5 w-1.5 rounded-full" style={{ backgroundColor: COLORS[i % COLORS.length] }} />{pretty(name)} <b className="ml-auto">{value}</b></span>)}</div></> : <p className="py-14 text-center text-xs text-muted-foreground">No requests yet.</p>}</Card><Card className="lg:col-span-3"><MiniTitle link="View all" to="/notifications">Notifications</MiniTitle><p className="-mt-2 mb-2 text-[11px] text-muted-foreground">{notifications.filter((n) => !n.read_at).length} unread</p><div className="divide-y">{notifications.slice(0, 4).map((n) => <div key={n.id} className="flex gap-2 py-2"><Bell className="mt-0.5 h-3 w-3 text-primary" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{n.title}</p><p className="truncate text-[10px] text-muted-foreground">{n.message || n.body}</p></div></div>)}{!notifications.length && <p className="py-8 text-center text-xs text-muted-foreground">No notifications.</p>}</div></Card></div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-5"><Card className="lg:col-span-3"><MiniTitle link="View all" to="/work-orders">Recent work orders</MiniTitle><div className="divide-y">{latest.length ? latest.slice(0, 5).map((wo) => <div key={wo.id} className="flex items-center justify-between gap-3 py-2.5"><div className="min-w-0"><p className="truncate text-xs font-semibold">{wo.title || wo.id}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{wo.work_order_number || wo.id} · {date(wo.due_at)}</p></div><div className="flex shrink-0 gap-1"><Pill className="text-[9px]" tone={statusTone(pretty(wo.priority))}>{pretty(wo.priority)}</Pill><Pill className="text-[9px]" tone={statusTone(pretty(wo.status))}>{pretty(wo.status)}</Pill></div></div>) : <p className="py-10 text-center text-xs text-muted-foreground">No work orders yet.</p>}</div></Card><Card className="lg:col-span-2"><MiniTitle>Recent activity</MiniTitle><div className="space-y-3">{latest.slice(0, 5).map((wo, i) => <div className="flex gap-2" key={wo.id}><i className="mt-1 h-1.5 w-1.5 rounded-full" style={{ backgroundColor: COLORS[i] }} /><p className="text-[10px] text-muted-foreground"><b className="text-foreground">{wo.work_order_number || wo.id}</b> status changed to {pretty(wo.status)}</p></div>)}{!latest.length && <p className="py-10 text-center text-xs text-muted-foreground">No activity yet.</p>}</div></Card></div>
  </div>;
}
function PlatformDashboard() { const [tenants, setTenants] = useState(null), [error, setError] = useState(""); const load = async () => { setError(""); try { setTenants((await listPlatformTenants()).data || []); } catch (e) { setError(e.message || "Could not load platform data."); } }; useEffect(() => { load(); }, []); if (!tenants && !error) return <LoadingDashboard />; if (error) return <ErrorState error={error} retry={load} />; const active = tenants.filter((t) => t.status === "ACTIVE").length; return <div className="space-y-4"><div className="grid grid-cols-3 gap-4"><StatCard icon={Database} label="Total tenants" value={tenants.length} /><StatCard icon={CheckCircle2} label="Active tenants" value={active} tone="success" /><StatCard icon={AlertTriangle} label="Provisioning" value={tenants.length - active} tone="warning" /></div><Card><MiniTitle>Recent tenants</MiniTitle>{tenants.map((t) => <div className="flex justify-between border-b py-3 text-sm" key={t.id}><span>{t.name}</span><Pill tone={statusTone(pretty(t.status))}>{pretty(t.status)}</Pill></div>)}</Card></div>; }
export default function Dashboard() { const { user } = useApp(); return <Reveal>{user.role === "super_admin" ? <PlatformDashboard /> : <TenantDashboard />}</Reveal>; }
