import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Check, Eye, Plus, Search } from "lucide-react";
import { toast } from "sonner";
import { useApp } from "../store/store";
import { Button, Card, Field, Input, Modal, Pill, Reveal, Select, Table, Textarea } from "../components/kit";
import { listAssets } from "../lib/assets";
import { listSites, listUsers } from "../lib/organization";
import { approveRequest, createRequest, getRequest, listRequests, rejectRequest } from "../lib/requests";

const PRIORITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
const pretty = (value) => String(value || "-").split("_").map((part) => part[0] + part.slice(1).toLowerCase()).join(" ");
const statusTone = (status) => ({ SUBMITTED: "primary", PENDING_APPROVAL: "warning", APPROVED: "success", CONVERTED: "accent", IN_PROGRESS: "accent", COMPLETED: "success", REJECTED: "danger", CANCELLED: "muted" }[status] || "muted");
const priorityTone = (priority) => ({ CRITICAL: "danger", HIGH: "warning", MEDIUM: "accent", LOW: "muted" }[priority] || "muted");
const formatDate = (date) => date ? new Intl.DateTimeFormat("en-US", { month: "numeric", day: "numeric", year: "numeric" }).format(new Date(date)) : "-";

export default function Requests() {
  const { user } = useApp(); const role = user?._backend?.membership?.roleKey || "";
  const [requests, setRequests] = useState([]), [assets, setAssets] = useState([]), [sites, setSites] = useState([]), [users, setUsers] = useState([]), [query, setQuery] = useState(""), [filter, setFilter] = useState("ALL"), [loading, setLoading] = useState(true), [form, setForm] = useState(null), [detail, setDetail] = useState(null), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [r, a, s, u] = await Promise.all([listRequests(), listAssets(), listSites(), listUsers()]); setRequests(r?.data || []); setAssets(a?.data || []); setSites(s?.data || []); setUsers(u?.data || []); } catch (e) { toast.error(e.message || "Unable to load maintenance requests."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const openDetail = async (item) => { try { setDetail((await getRequest(item.id)).data); } catch (e) { toast.error(e.message || "Unable to load request detail."); } };
  const tabs = ["ALL", "SUBMITTED", "PENDING_APPROVAL", "APPROVED", "CONVERTED", "IN_PROGRESS", "COMPLETED", "REJECTED"];
  const rows = useMemo(() => requests.filter((r) => (filter === "ALL" || r.status === filter) && `${r.request_number} ${r.title}`.toLowerCase().includes(query.toLowerCase())), [requests, filter, query]);
  const submit = async () => { if (!form.asset_id || !form.title.trim() || !form.description.trim()) return toast.error("Category, title, and description are required."); setSaving(true); try { await createRequest({ asset_id: form.asset_id, title: form.title.trim(), description: `${form.location ? `Location: ${form.location}\n\n` : ""}${form.description.trim()}`, priority: form.priority }); toast.success("Maintenance request submitted."); setForm(null); load(); } catch (e) { toast.error(e.message || "Request could not be submitted."); } finally { setSaving(false); } };
  const action = async (name) => { const reason = name === "reject" ? window.prompt("Reason for rejection") : null; if (name === "reject" && !reason) return; try { if (name === "approve") await approveRequest(detail.id, {}); else await rejectRequest(detail.id, reason); toast.success("Request updated."); setDetail(null); load(); } catch (e) { toast.error(e.message || "Action failed."); } };
  const columns = [
    { key: "request_number", header: "ID", render: (r) => <span className="font-mono text-[11px] text-muted-foreground">{r.request_number}</span> }, { key: "title", header: "Title", render: (r) => <span className="font-semibold">{r.title}</span> },
    { key: "status", header: "Status", render: (r) => <Pill tone={statusTone(r.status)}><i className="h-1.5 w-1.5 rounded-full bg-current" />{pretty(r.status)}</Pill> }, { key: "priority", header: "Priority", render: (r) => <Pill tone={priorityTone(r.priority)}>{pretty(r.priority)}</Pill> },
    { key: "site", header: "Site", render: (r) => r.asset?.site?.name || r.site?.name || sites.find((s) => s.id === assets.find((a) => a.id === r.asset_id)?.site_id)?.name || "-" }, { key: "requester", header: "Submitted by", render: (r) => r.requester?.full_name || r.submitted_by?.full_name || users.find((u) => u.id === r.requester_id || u.id === r.created_by)?.full_name || "-" }, { key: "reported_at", header: "Date", render: (r) => formatDate(r.reported_at || r.created_at) },
    { key: "action", header: "Action", render: (r) => <button onClick={(e) => { e.stopPropagation(); openDetail(r); }} className="inline-flex items-center gap-1 text-xs font-semibold text-primary"><Eye className="h-3.5 w-3.5" /> View detail</button> },
  ];
  return <Reveal className="mx-auto max-w-[1200px]"><Card className="overflow-hidden p-0"><div className="flex flex-col gap-4 px-4 py-5 lg:px-5 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-display text-base font-bold">Maintenance requests</h2><p className="mt-0.5 text-sm text-muted-foreground">Submit and track maintenance requests</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search..." className="w-40 rounded-xl border bg-background py-2 pl-8 pr-3 text-xs outline-none focus:ring-2 focus:ring-primary/20" /></div><Button className="px-3 py-2 text-xs" onClick={() => setForm({ asset_id: assets[0]?.id || "", title: "", priority: "MEDIUM", location: "", description: "" })} disabled={!assets.length}><Plus className="h-3.5 w-3.5" /> New request</Button></div></div><div className="flex gap-1.5 overflow-x-auto border-b px-4 pb-4 lg:px-5">{tabs.map((tab) => <button key={tab} onClick={() => setFilter(tab)} className={`shrink-0 rounded-full px-3 py-1 text-[10px] font-bold ${filter === tab ? "bg-primary text-white" : "bg-muted text-muted-foreground"}`}>{tab === "ALL" ? "All" : pretty(tab)}</button>)}</div><Table columns={columns} rows={rows} onRowClick={openDetail} empty={loading ? "Loading..." : "No maintenance requests found."} /></Card>
  <Modal open={!!form} onClose={() => setForm(null)} title="New maintenance request" footer={<><Button variant="ghost" className="border-0 bg-transparent px-3 py-2 text-xs" onClick={() => setForm(null)}>Cancel</Button><Button className="px-3 py-2 text-xs" onClick={submit} disabled={saving}>{saving ? "Submitting..." : "Submit request"}</Button></>}>{form && <div className="space-y-3"><div className="rounded-xl bg-muted/50 px-3 py-3 text-[11px] text-muted-foreground">Submitting as <b className="text-foreground">{user?.name}</b> · Jakarta HQ</div><Field label="Title"><Input placeholder="Brief description of the issue" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label="Category"><Select value={form.asset_id} onChange={(e) => setForm({ ...form, asset_id: e.target.value })}><option value="">Select...</option>{assets.map((a) => <option key={a.id} value={a.id}>{a.asset_category?.name || a.category?.name || a.name}</option>)}</Select></Field><Field label="Priority"><Select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="">Select...</option>{PRIORITIES.map((p) => <option key={p} value={p}>{pretty(p)}</option>)}</Select></Field><Field label="Location"><Input placeholder="Specific location within the site" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></Field><Field label="Description"><Textarea rows={4} placeholder="Detailed description..." value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field></div>}</Modal>
  <Modal open={!!detail} onClose={() => setDetail(null)} title={detail ? `${detail.request_number}: ${detail.title}` : "Maintenance request"} footer={<Button variant="ghost" onClick={() => setDetail(null)}>Close</Button>}>{detail && <div className="space-y-4"><div className="flex gap-2"><Pill tone={statusTone(detail.status)}>{pretty(detail.status)}</Pill><Pill tone={priorityTone(detail.priority)}>{pretty(detail.priority)}</Pill></div><p className="text-sm text-muted-foreground">{detail.description}</p><div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-xs text-muted-foreground">Site</p><b>{detail.asset?.site?.name || "-"}</b></div><div><p className="text-xs text-muted-foreground">Asset</p><b>{detail.asset?.name || "-"}</b></div><div><p className="text-xs text-muted-foreground">Requested by</p><b>{detail.requester?.full_name || "-"}</b></div><div><p className="text-xs text-muted-foreground">Submitted</p><b>{formatDate(detail.reported_at || detail.created_at)}</b></div></div>{role === "MANAGER" && detail.status === "PENDING_APPROVAL" && <div className="flex gap-2 border-t pt-4"><Button variant="danger" onClick={() => action("reject")}>Reject</Button><Button onClick={() => action("approve")}><Check className="h-4 w-4" /> Approve & Create WO</Button></div>}</div>}</Modal></Reveal>;
}
