import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Plus, Search, Eye } from "lucide-react";
import { toast } from "sonner";
import { useApp } from "../store/store";
import { PageHeader, Card, Button, Modal, ConfirmDialog, Field, Input, Select, Reveal } from "../components/kit";
import { listUsers, createUser, updateUser } from "../lib/organization";
import { listWorkOrders } from "../lib/workorders";

const ROLE_OPTIONS = [{ value: "TECHNICIAN", label: "Technician" }, { value: "SUPERVISOR", label: "Supervisor" }];
const blank = { full_name: "", email: "", phone: "", employee_code: "", role_key: "TECHNICIAN", primary_site_id: "", temporary_password: "" };

export default function Technicians() {
  const { user } = useApp(); const canEdit = user?.role === "company_admin" || user?.role === "manager";
  const [loading, setLoading] = useState(true); const [technicians, setTechnicians] = useState([]); const [workOrders, setWorkOrders] = useState([]); const [sites, setSites] = useState([]);
  const [form, setForm] = useState(null); const [del, setDel] = useState(null); const [selected, setSelected] = useState(null); const [saving, setSaving] = useState(false); const [query, setQuery] = useState(""); const [availability, setAvailability] = useState("all");
  const load = useCallback(async () => { setLoading(true); try { const [techRes, woRes, sitesRes] = await Promise.all([listUsers({ role: "TECHNICIAN", status: "ACTIVE", per_page: 100 }), listWorkOrders({ per_page: 100 }), import("../lib/assets").then((m) => m.listSites())]); setTechnicians(techRes.data || []); setWorkOrders(woRes.data || []); setSites(sitesRes.data || []); } catch (err) { toast.error(err.message || "Gagal memuat data teknisi."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const activeWoCount = (id) => workOrders.filter((w) => w.current_assignee_id === id && !["COMPLETED", "CLOSED", "CANCELLED"].includes(w.status)).length;
  const completedWoCount = (id) => workOrders.filter((w) => w.current_assignee_id === id && ["COMPLETED", "CLOSED"].includes(w.status)).length;
  const loadPct = (id) => Math.min(Math.round((activeWoCount(id) / 5) * 100), 100); const statusFor = (t) => activeWoCount(t.id) ? "busy" : "available"; const initials = (n) => (n || "?").split(" ").map((w) => w[0]).slice(0, 2).join("").toUpperCase();
  const filtered = useMemo(() => technicians.filter((t) => `${t.full_name || ""} ${t.email || ""} ${t.employee_code || ""}`.toLowerCase().includes(query.toLowerCase()) && (availability === "all" || statusFor(t) === availability)), [technicians, workOrders, query, availability]);
  const save = async () => { if (!form.full_name?.trim() || !form.email?.trim()) return toast.error("Nama dan email wajib diisi."); if (!form.id && !form.temporary_password?.trim()) return toast.error("Password sementara wajib diisi untuk user baru."); setSaving(true); try { if (form.id) await updateUser(form.id, { full_name: form.full_name.trim(), phone: form.phone || null, employee_code: form.employee_code || null, role_key: form.role_key, primary_site_id: form.primary_site_id || null }); else await createUser({ full_name: form.full_name.trim(), email: form.email.trim(), phone: form.phone || null, employee_code: form.employee_code || null, role_key: form.role_key, primary_site_id: form.primary_site_id || null, temporary_password: form.temporary_password }); toast.success(form.id ? "Teknisi diperbarui." : "Teknisi ditambahkan."); setForm(null); load(); } catch (err) { toast.error(err.message || "Gagal menyimpan teknisi."); } finally { setSaving(false); } };
  const confirmDel = async () => { try { await updateUser(del.id, { status: "INACTIVE" }); toast.success("Teknisi dinonaktifkan."); setDel(null); load(); } catch (err) { toast.error(err.message || "Gagal menonaktifkan teknisi."); } };
  const Badge = ({ tech }) => { const busy = statusFor(tech) === "busy"; return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] font-semibold ${busy ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}><i className={`h-1.5 w-1.5 rounded-full ${busy ? "bg-amber-500" : "bg-emerald-500"}`} />{busy ? "Busy" : "Available"}</span>; };
  return <Reveal><PageHeader title="Manajemen Teknisi" subtitle={`${technicians.length} teknisi terdaftar`} action={canEdit && <Button onClick={() => setForm({ ...blank, primary_site_id: sites[0]?.id || "" })}><Plus className="h-4 w-4" /> Tambah Teknisi</Button>} />
    <div className="mb-4 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><label className="relative block max-w-xs flex-1"><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari nama, keahlian..." className="h-9 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-xs outline-none focus:border-blue-500" /></label><div className="flex gap-1 rounded-lg bg-slate-50 p-1 text-xs">{[["all", "Semua"], ["available", "Available"], ["busy", "Busy"], ["off", "Off Duty"]].map(([key, label]) => <button key={key} onClick={() => setAvailability(key)} className={`rounded-md px-3 py-1.5 ${availability === key ? "bg-white font-semibold shadow-sm" : "text-slate-500"}`}>{label}</button>)}</div><div className="text-[10px] text-slate-400"><span className="text-emerald-600">● {technicians.filter((t) => statusFor(t) === "available").length} Tersedia</span> <span className="ml-2 text-amber-600">● {technicians.filter((t) => statusFor(t) === "busy").length} Sibuk</span> <span className="ml-2">● 0 Off</span></div></div></div>
    <Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b border-slate-100 bg-slate-50/70 text-[10px] uppercase tracking-wide text-slate-500"><tr>{["Teknisi", "Departemen", "Keahlian", "Ketersediaan", "WO Aktif", "Beban", "Rating", ""].map((h) => <th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading && <tr><td colSpan="8" className="px-4 py-10 text-center text-slate-400">Memuat...</td></tr>}{!loading && !filtered.length && <tr><td colSpan="8" className="px-4 py-10 text-center text-slate-400">Belum ada teknisi terdaftar.</td></tr>}{filtered.map((t) => <tr key={t.id} className="hover:bg-slate-50/70"><td className="px-4 py-3"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-600 text-[10px] font-bold text-white">{initials(t.full_name)}</div><div><div className="font-semibold text-slate-800">{t.full_name}</div><div className="text-[10px] text-slate-400">{t.email}</div></div></div></td><td className="px-4 py-3 text-slate-500">{t.department || t.role_key || "—"}</td><td className="px-4 py-3"><span className="rounded bg-blue-50 px-2 py-1 text-[10px] text-blue-600">{t.specialty || t.employee_code || "—"}</span></td><td className="px-4 py-3"><Badge tech={t} /></td><td className="px-4 py-3 font-semibold">{activeWoCount(t.id)}</td><td className="px-4 py-3"><div className="flex items-center gap-2"><div className="h-1.5 w-12 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${loadPct(t.id) > 60 ? "bg-amber-500" : "bg-emerald-500"}`} style={{ width: `${loadPct(t.id)}%` }} /></div><span className="text-[10px] text-slate-400">{loadPct(t.id)}%</span></div></td><td className="px-4 py-3 text-slate-500">—</td><td className="px-4 py-3"><button onClick={() => setSelected(t)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10px] text-slate-600 hover:border-blue-300 hover:text-blue-600"><Eye className="h-3 w-3" /> Detail</button></td></tr>)}</tbody></table></div></Card>
    {/* TODO: butuh data backend untuk rating, shift, sertifikasi, dan status Off Duty. */}
    <Modal open={!!selected} onClose={() => setSelected(null)} title="Detail Teknisi" wide>{selected && <div className="grid gap-4 lg:grid-cols-[280px_1fr]"><div className="space-y-4"><Card className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-blue-600 text-xl font-bold text-white">{initials(selected.full_name)}</div><h3 className="mt-3 text-lg font-bold">{selected.full_name}</h3><p className="text-xs text-slate-500">{selected.role_key}</p><div className="mt-3"><Badge tech={selected} /></div><div className="mt-5 space-y-2 border-t pt-4 text-left text-xs"><p><span className="text-slate-400">Email</span><br />{selected.email || "—"}</p><p><span className="text-slate-400">Telepon</span><br />{selected.phone || "—"}</p><p><span className="text-slate-400">Site</span><br />{sites.find((s) => s.id === selected.primary_site_id)?.name || "—"}</p></div></Card><Card><h4 className="font-semibold">Keahlian</h4><p className="mt-3 text-xs text-slate-400">{selected.specialty || "—"}</p></Card><Card><h4 className="font-semibold">Sertifikasi</h4><p className="mt-3 text-xs text-slate-400">—</p></Card></div><div className="space-y-4"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[[completedWoCount(selected.id), "WO Selesai", "text-emerald-600"], [activeWoCount(selected.id), "WO Aktif", "text-blue-600"], ["—", "Rating", "text-amber-600"], ["—", "Avg Jam/WO", "text-violet-600"]].map(([value, label, tone]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4 text-center"><div className={`text-xl font-bold ${tone}`}>{value}</div><div className="text-[10px] text-slate-400">{label}</div></div>)}</div><Card><div className="flex justify-between"><h4 className="font-semibold">Beban Kerja Saat Ini</h4><span className="text-xs text-slate-400">{loadPct(selected.id)}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-500" style={{ width: `${loadPct(selected.id)}%` }} /></div></Card><Card><h4 className="font-semibold">Work Order Aktif ({activeWoCount(selected.id)})</h4>{workOrders.filter((w) => w.current_assignee_id === selected.id && !["COMPLETED", "CLOSED", "CANCELLED"].includes(w.status)).map((wo) => <div key={wo.id} className="mt-3 rounded-lg bg-slate-50 p-3 text-xs"><b>{wo.title}</b><div className="text-[10px] text-slate-400">{wo.due_at || "—"}</div></div>)}{!activeWoCount(selected.id) && <p className="py-4 text-center text-xs text-slate-400">Tidak ada WO aktif.</p>}</Card><Card><h4 className="font-semibold">Riwayat WO</h4><p className="py-6 text-center text-xs text-slate-400">Belum ada riwayat.</p></Card></div></div>}</Modal>
    <Modal open={!!form} onClose={() => setForm(null)} title={form?.id ? "Edit Teknisi" : "Tambah Teknisi"} wide footer={<><Button variant="ghost" onClick={() => setForm(null)}>Batal</Button><Button onClick={save} disabled={saving}>{saving ? "Menyimpan..." : "Simpan"}</Button></>}>{form && <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Nama Lengkap" required><Input value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} /></Field>{!form.id && <Field label="Email" required><Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field>}<Field label="Telepon"><Input value={form.phone || ""} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></Field><Field label="Kode Karyawan"><Input value={form.employee_code || ""} onChange={(e) => setForm({ ...form, employee_code: e.target.value })} /></Field><Field label="Peran"><Select value={form.role_key} onChange={(e) => setForm({ ...form, role_key: e.target.value })}>{ROLE_OPTIONS.map((r) => <option key={r.value} value={r.value}>{r.label}</option>)}</Select></Field><Field label="Site Utama"><Select value={form.primary_site_id || ""} onChange={(e) => setForm({ ...form, primary_site_id: e.target.value })}><option value="">Tidak ditentukan</option>{sites.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</Select></Field>{!form.id && <div className="sm:col-span-2"><Field label="Password Sementara" required><Input type="password" value={form.temporary_password} onChange={(e) => setForm({ ...form, temporary_password: e.target.value })} placeholder="Min. 8 karakter" /></Field></div>}</div>}</Modal>
    <ConfirmDialog open={!!del} onClose={() => setDel(null)} onConfirm={confirmDel} title="Nonaktifkan Teknisi" message={`Nonaktifkan "${del?.full_name}"? Status akan diubah menjadi INACTIVE.`} />
  </Reveal>;
}
