<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Support\ApiData;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * Rule-based reliability & cost analytics — same philosophy as
 * SupportController::insights(): every number here is computed directly
 * from work_orders/assets/inventory rows the tenant actually has, never
 * estimated or faked. If a metric needs data the schema doesn't capture
 * (e.g. labor cost — there is no hourly rate anywhere), it is simply
 * omitted rather than guessed.
 *
 * Definitions used throughout (documented so the numbers are auditable):
 *  - "Planned" work order  = source 'PM' (generated by a PM schedule).
 *  - "Unplanned" work order = source 'DIRECT' or 'REQUEST' (breakdown/ad-hoc).
 *    This is the closest honest proxy for "failure" this schema supports,
 *    since there is no dedicated failure/breakdown event table.
 *  - MTTR = mean(completed_at - reported_at) over unplanned work orders
 *    that have completed_at set, within the window.
 *  - MTBF = for each asset with 2+ unplanned work orders in the window,
 *    the mean interval between consecutive reported_at timestamps; the
 *    fleet figure is the mean of those per-asset means. Assets with fewer
 *    than 2 unplanned work orders in the window are excluded (not enough
 *    data to infer an interval) rather than assumed to be 0 or infinite.
 *  - Downtime hours = sum(completed_at - reported_at) over completed
 *    unplanned work orders in the window.
 *  - Uptime % = 1 - (downtime hours / (active asset count × window hours)),
 *    clamped to [0, 100].
 */
class AnalyticsController extends Controller
{
    public function reliability(Request $request): mixed
    {
        $windowDays = max(7, min(365, $request->integer('window_days', 180)));
        $since = now()->subDays($windowDays);

        $activeAssetCount = DB::table('assets')->whereNull('archived_at')->count();

        $workOrders = DB::table('work_orders')
            ->where('created_at', '>=', $since)
            ->select('id', 'asset_id', 'source', 'status', 'reported_at', 'completed_at', 'created_at')
            ->get();

        $unplanned = $workOrders->whereIn('source', ['DIRECT', 'REQUEST']);
        $planned = $workOrders->where('source', 'PM');
        $unplannedCompleted = $unplanned->filter(fn ($r) => $r->completed_at !== null);

        // ---- fleet MTTR ----
        $repairHours = $unplannedCompleted->map(
            fn ($r) => Carbon::parse($r->reported_at)->diffInMinutes(Carbon::parse($r->completed_at), false) / 60
        )->filter(fn ($h) => $h >= 0);
        $fleetMttrHours = $repairHours->isEmpty() ? null : round($repairHours->avg(), 1);

        // ---- fleet MTBF: per-asset mean interval between unplanned events, then averaged ----
        $assetIntervals = $unplanned->groupBy('asset_id')->map(function ($group) {
            $sorted = $group->sortBy('reported_at')->values();
            if ($sorted->count() < 2) {
                return null;
            }
            $diffs = [];
            for ($i = 1; $i < $sorted->count(); $i++) {
                $diffs[] = Carbon::parse($sorted[$i - 1]->reported_at)->diffInMinutes(Carbon::parse($sorted[$i]->reported_at), false) / 60;
            }

            return collect($diffs)->avg();
        })->filter(fn ($v) => $v !== null && $v >= 0);
        $fleetMtbfHours = $assetIntervals->isEmpty() ? null : round($assetIntervals->avg(), 1);

        // ---- downtime & uptime ----
        $totalDowntimeHours = $repairHours->sum();
        $windowHours = $windowDays * 24;
        $possibleHours = max(1, $activeAssetCount) * $windowHours;
        $uptimePct = $activeAssetCount > 0
            ? round(max(0, min(100, (1 - ($totalDowntimeHours / $possibleHours)) * 100)), 2)
            : null;

        // ---- planned vs unplanned ratio ----
        $totalWorkOrders = $workOrders->count();
        $plannedRatioPct = $totalWorkOrders > 0 ? round(($planned->count() / $totalWorkOrders) * 100, 1) : null;

        // ---- parts cost, from real stock-out movements linked to work orders ----
        $partsCostRows = DB::table('spare_part_stock_movements')
            ->join('spare_parts', 'spare_parts.id', '=', 'spare_part_stock_movements.spare_part_id')
            ->where('spare_part_stock_movements.type', 'OUT')
            ->where('spare_part_stock_movements.reference_type', 'WORK_ORDER')
            ->where('spare_part_stock_movements.created_at', '>=', $since)
            ->select(
                'spare_part_stock_movements.created_at',
                'spare_part_stock_movements.quantity',
                'spare_parts.unit_cost',
            )
            ->get();
        $totalPartsCost = $partsCostRows->sum(fn ($r) => abs($r->quantity) * (float) ($r->unit_cost ?? 0));
        // spare_parts has no currency_code column — this tenant app is IDR-only everywhere else too.
        $currencyCode = 'IDR';

        // ---- labor hours, from real technician time entries ----
        $laborRows = DB::table('work_order_labor_entries')
            ->join('work_orders', 'work_orders.id', '=', 'work_order_labor_entries.work_order_id')
            ->where('work_order_labor_entries.started_at', '>=', $since)
            ->whereNotNull('work_order_labor_entries.duration_minutes')
            ->select('work_order_labor_entries.started_at', 'work_order_labor_entries.duration_minutes')
            ->get();
        $totalLaborHours = round($laborRows->sum('duration_minutes') / 60, 1);

        // ---- monthly trend (bounded to at most 12 buckets) ----
        $monthCount = min(12, (int) ceil($windowDays / 30));
        $months = collect(range($monthCount - 1, 0))->map(fn ($i) => now()->subMonths($i)->startOfMonth());
        $monthly = $months->map(function (Carbon $monthStart) use ($unplanned, $planned, $partsCostRows, $laborRows, $activeAssetCount) {
            $monthEnd = (clone $monthStart)->endOfMonth();
            $inMonth = fn ($ts) => $ts && Carbon::parse($ts)->between($monthStart, $monthEnd);

            $unplannedInMonth = $unplanned->filter(fn ($r) => $inMonth($r->reported_at));
            $unplannedCompletedInMonth = $unplannedInMonth->filter(fn ($r) => $r->completed_at !== null);
            $repairHoursInMonth = $unplannedCompletedInMonth->map(
                fn ($r) => Carbon::parse($r->reported_at)->diffInMinutes(Carbon::parse($r->completed_at), false) / 60
            )->filter(fn ($h) => $h >= 0);
            $downtimeHoursInMonth = $repairHoursInMonth->sum();
            $monthPossibleHours = max(1, $activeAssetCount) * $monthStart->diffInHours($monthEnd);

            return [
                'month' => $monthStart->format('Y-m'),
                'label' => $monthStart->translatedFormat('M Y'),
                'planned_count' => $planned->filter(fn ($r) => $inMonth($r->reported_at))->count(),
                'unplanned_count' => $unplannedInMonth->count(),
                'mttr_hours' => $repairHoursInMonth->isEmpty() ? null : round($repairHoursInMonth->avg(), 1),
                'downtime_hours' => round($downtimeHoursInMonth, 1),
                'uptime_pct' => $activeAssetCount > 0 ? round(max(0, min(100, (1 - ($downtimeHoursInMonth / $monthPossibleHours)) * 100)), 2) : null,
                'parts_cost' => round($partsCostRows->filter(fn ($r) => $inMonth($r->created_at))->sum(fn ($r) => abs($r->quantity) * (float) ($r->unit_cost ?? 0)), 2),
                'labor_hours' => round($laborRows->filter(fn ($r) => $inMonth($r->started_at))->sum('duration_minutes') / 60, 1),
            ];
        })->values();

        return ApiData::item([
            'window_days' => $windowDays,
            'generated_at' => now(),
            'method' => 'rule_based',
            'definitions' => [
                'planned' => "source = 'PM'",
                'unplanned' => "source IN ('DIRECT','REQUEST')",
                'mttr' => 'mean(completed_at - reported_at) over completed unplanned work orders',
                'mtbf' => 'mean per-asset interval between consecutive unplanned work orders (assets with 2+ events only)',
                'uptime' => '1 - (downtime hours / (active assets × window hours))',
            ],
            'fleet' => [
                'active_asset_count' => $activeAssetCount,
                'total_work_orders' => $totalWorkOrders,
                'planned_work_orders' => $planned->count(),
                'unplanned_work_orders' => $unplanned->count(),
                'planned_ratio_pct' => $plannedRatioPct,
                'mttr_hours' => $fleetMttrHours,
                'mtbf_hours' => $fleetMtbfHours,
                'mtbf_asset_sample_size' => $assetIntervals->count(),
                'total_downtime_hours' => round($totalDowntimeHours, 1),
                'uptime_pct' => $uptimePct,
                'total_parts_cost' => round($totalPartsCost, 2),
                'currency_code' => $currencyCode,
                'total_labor_hours' => $totalLaborHours,
            ],
            'monthly' => $monthly,
        ]);
    }
}
